# https://github.com/realm/jazzy

author: Ryo Aoyama
author_url: https://github.com/ra1028
github_url: https://github.com/ra1028/Carbon
module: Carbon
readme: README.md
output: docs
theme: fullwidth
clean: true
xcodebuild_arguments:
  - -workspace
  - Carbon.xcworkspace
  - -scheme
  - Carbon
custom_categories:
  - name: Element
    children:
      - Component
      - IdentifiableComponent
      - AnyComponent
      - Section
      - Group
  - name: ComponentWrapper
    children:
      - IdentifiedComponentWrapper
      - ComponentWrapping
  - name: Node
    children:
      - CellNode
      - ViewNode
  - name: Renderer
    children:
      - Renderer
  - name: Adapter
    children:
      - Adapter
      - UITableViewAdapter
      - UICollectionViewAdapter
      - UICollectionViewFlowLayoutAdapter
  - name: Updater
    children:
      - Updater
      - UITableViewUpdater
      - UITableViewReloadDataUpdater
      - UICollectionViewUpdater
      - UICollectionViewReloadDataUpdater
  - name: Interface
    children:
      - ComponentRenderable
      - UITableViewComponentCell
      - UITableViewComponentHeaderFooterView
      - UICollectionViewComponentCell
      - UICollectionComponentReusableView
  - name: Builder
    children:
      - CellsBuilder
      - SectionsBuilder
      - CellsBuildable
      - SectionsBuildable
      - Optional
  - name: Changeset
    children:
      - DataChangeset
      - StagedDataChangeset
