# https://github.com/realm/SwiftLint

excluded:
  - Carthage
  - Pods
  - Examples/Example-iOS/Pods

disabled_rules:
  - type_name
  - identifier_name
  - force_cast
  - xctfail_message

nesting:
  type_level:
    warning: 2

line_length:
  warning: 200

file_length:
  warning: 600

type_body_length:
  warning: 400

function_body_length:
  warning: 50

cyclomatic_complexity:
  warning: 12

statement_position:
  statement_mode: uncuddled_else
